rest_server: 
  host: localhost
  port: 7098

tcp_server:
  host: localhost
  port: 6979

db:
  host: vts_db
  port: 27018
  user: 
  pwd :

redis:
  host: vts_redis
  port: 6379

tile38:
  host: vts_tile38
  port: 9851

rabbitmq:
  host: vts_rmq
  port: 5671